language: minimal
services:
  - docker
script:
  - cd build \
    && make build \
    && cd ..
  - cd single \
    && make configure SILENT=1 CONFIGURE_OPTS="-e SETTING_ACTIVATE_NOTES=1 -e SETTING_ACTIVATE_XQUEUE=1" \
    && make databases \
    && make assets \
    && cd ..
deploy:
  provider: script
  script: cd build/ && docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && make push
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|release\/.*$
